name: productivity
services:
  productivity:
    container_name: productivity-app
    image: productivity:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
networks:
  default:
    name: productivity_default